[package]
org = "madushanka"
name = "police_api"
version = "0.1.1"
distribution = "2201.2.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
  groupId = "mysql"
  artifactId = "mysql-connector-java"
  version = "8.0.20"
